### ISSUE TITLE
updateRobotState fail callback isn't triggering?

### ISSUE THREAD

**Issue by doschuster** [NeatoRobotics/neato-sdk-android#1]
Hello,

i'm trying to use your [updateRobotState](https://github.com/NeatoRobotics/neato-sdk-android/blob/master/Neato-SDK/neato-sdk-android/src/main/java/com/neatorobotics/sdk/android/NeatoRobot.java#L61) method. But i have the issue that when the robot is offline the fail callback in updateRobotState isn't triggering. I get the response from the nucleo API:
`D/JSON output from POST https://nucleo.neatocloud.com:4443: {"message":"Could not find robot_serial for specified vendor_name"}`
`D/NucleoBaseClient: RESPONSE HTTP CODE : 404`
or
`D/JSON output from POST https://nucleo.neatocloud.com:4443: {"message":"Timeout waiting a response from robot"}`
`D/NucleoBaseClient: RESPONSE HTTP CODE : 504`

If the Robot is online i recieve a `RESPONSE HTTP CODE : 200` and the done callback is triggering properly.

Isn't in [asyncCall.executeCall](https://github.com/NeatoRobotics/neato-sdk-android/blob/master/Neato-SDK/neato-sdk-android/src/main/java/com/neatorobotics/sdk/android/NeatoRobot.java#L63) the fail method missing that get's triggert when [executeCall](https://github.com/NeatoRobotics/neato-sdk-android/blob/master/Neato-SDK/neato-sdk-android/src/main/java/com/neatorobotics/sdk/android/NeatoRobot.java#L472) calls callback.fail? Or am i stupid?

In your docs it says to updateRobotState.fail  `        //the robot maybe OFFLINE or in ERROR state
        //check the NeatoError for details` but this never occurs. Is it a Bug or just a Bug in my system?

**Comment by marcouberti** [comment]
Hi, 
sorry for the late reply. You are right the fail callback is never called. I fixed it in the 0.8.1 version. You can install it using Gradle as before. Thank you for find this bug.

Best,
Marco
